18_while_demo.sh
19_until_loop.sh
20_infinite_loop.sh
21_infinite_for_loop.sh
22_while_with_file.sh
23_test.csv
23_while_with_loop.sh
24_function_demo.sh
25_function_with_cal.sh
26_args.sh
27_shift_args.sh
28_break.sh
29_continue.sh
30_connectivity_check.sh
31_file_exit_check.sh
32_dice.random.sh
33_root_usercheck.sh
34_redirect_dns.sh
all_files.sh
exit.sh
names.txt
redirect.log
